### ISSUE TITLE
JS document.getElementByID

### ISSUE THREAD

**Issue by jlw365** [eecs394-s18/ClassConfusion-Refactor#11]
In most of our .ts files, there is an attempt to send variables to the associated HTML using document.getElementById(). It's giving errors such as can't get innerHTML and stuff. I'm not sure if this line is just in the wrong place in the file or if it's better practice to use a different method with Ionic and it would be helpful to fix this.  

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

**Comment by bdscharf** [comment]
Probably best to use ngModels for these elements within the HTML. 

Check out line 24 [here](https://github.com/eecs394-s18/ClassConfusion-Refactor/blob/master/src/pages/topics-p/topics-p.html) for a general idea of how that looks in the HTML. Those ngModels  should just be able to directly reference the lectureName and className variables from topics-[].ts in lines 18 and 19 [here](https://github.com/eecs394-s18/ClassConfusion-Refactor/blob/master/src/pages/topics-p/topics-p.ts).
