### ISSUE TITLE
Add comment box within student topic list

### ISSUE THREAD

**Issue by jlw365** [eecs394-s18/ClassConfusion-Refactor#20]

**Comment by bdscharf** [comment]
[https://ionicframework.com/docs/ionicons/]("chat-bubbles" icon is cool)

**Comment by bdscharf** [comment]
new branch feature/comments

**Comment by bdscharf** [comment]
@davjung make some comments appear on the results page

**Comment by bdscharf** [comment]
display completed in PRs #30 and #31
